name: Refresh goreportcard

inputs:
  repo:
    description: "Url of the repo to update. Defaults to current one."
    required: false
    default: "github.com/${{ github.repository }}"

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        curl "https://goreportcard.com/checks" \
          -X POST \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "repo=${{ inputs.repo }}"
